/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

export const index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    dependencies: ["tw-animate-css","class-variance-authority","lucide-react"],
    devDependencies: undefined,
    registryDependencies: ["utils"],
    files: [],
    keywords: [],
    component: null,
    command: '@animate-ui/index',
  },
  "hello-world": {
    name: "hello-world",
    description: "Hello World Description",
    type: "registry:component",
    dependencies: [],
    devDependencies: [],
    registryDependencies: [],
    files: [
  {
    "path": "registry/foliokit/hello-world/index.tsx",
    "type": "registry:ui",
    "target": "components/foliokit/hello-world/hello-world.tsx",
    "content": "export function HelloWorld() {\r\n  return <h1 className=\"text-2xl font-bold\">Hello World</h1>\r\n}"
  }
],
    keywords: [],
    component: (function() {
      const LazyComp = React.lazy(async () => {
        const mod = await import("@/registry/foliokit/hello-world/index.tsx");
        const exportName = Object.keys(mod).find(
          key => typeof mod[key] === 'function' || typeof mod[key] === 'object'
        ) || "hello-world";
        const Comp = mod.default || mod[exportName];
        if (mod.animations) {
          (LazyComp as any).animations = mod.animations;
        }
        return { default: Comp };
      });
      LazyComp.demoProps = {};
      return LazyComp;
    })(),
    command: '@animate-ui/hello-world',
  },
  }